// app/(main)/layout.css
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"; 
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                suppressHydrationWarning={true}
        >
            <Theme>
              <div className="bg-[#F4F4F4] min-h-screen p-0 m-0">
                <div className="border-x-2 mx-32 border-gray-200 min-h-screen ">
                {children}
                </div>
              </div>
          </Theme>
      </body>
    </html>
  );
}
